### ISSUE TITLE
Force torque Sensor stream at 5 Hz

### ISSUE THREAD

**Issue by nitish3693** [Extend-Robotics/xarm_ros#1]
Need to increase the frequency of the sensor.

**Comment by nitish3693** [comment]
The publisher for the torque could be found in the https://github.com/xArm-Developer/xarm_ros/blob/c10d5e59dd50109d15e8fbd3da0bae6aeacbb855/xarm_api/src/xarm_driver.cpp

**Comment by nitish3693** [comment]
On analysing the driver code, it was discovered that the publisher is in function
```
    void XArmDriver::pub_ftsensor_ext_state(geometry_msgs::WrenchStamped &wrench_msg)
    {
        ftsensor_ext_state_.publish(wrench_msg);
    }
```

which is called by function `XArmDriver::_report_data_callback` on the condition 

```
        if ((report_type_ == "dev" && report_data_ptr->total_num >= 135) 
            || (report_type_ == "rich" && report_data_ptr->total_num >= 481))
```

**Comment by nitish3693** [comment]
Tested with `report_type = dev` 

Result : 

![image](https://user-images.githubusercontent.com/75649112/205619173-e0435751-a7f8-458d-a47a-c9262ed341d6.png)

**Comment by Changliu52** [comment]
@nitish3693 Has this been completed?

**Comment by nitish3693** [comment]
The xarm6 and xarm7 launch files are updated to use the report type as "dev" as shown in 
https://github.com/Extend-Robotics/extend_bio_ik/blob/bbac1250760a116f6c7e705f632d08d8947eb60a/bio_ik_service/bio_ik_service_examples/launch/all_xarm6_gripper.launch#LL4C1-L4C41

and 

https://github.com/Extend-Robotics/extend_bio_ik/blob/bbac1250760a116f6c7e705f632d08d8947eb60a/bio_ik_service/bio_ik_service_examples/launch/all_xarm7_gripper.launch#L4
